#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1359485719                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://www.flicktype.com/sdk/            # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : The best typing experience on Apple Watch.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Kosta Eleftheriou                               
your_link                                 : https://www.flicktype.com
your_city                                 : California☀️                                
email_address                             : hello@flicktype.com
facebook_username                         : flicktype
instagram_username                        : flicktype
twitter_username                          : flicktype
github_username                           : flicktype
youtube_username                          : flicktype



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : “Best of 2020”
    description                           : Apple
    fontawesome_icon_name                 : magic
    
  - title                                 : Powerful Auto-Correct
    description                           : Makes typing easy and comfortable.
    fontawesome_icon_name                 : mobile

  - title                                 : Swipe Typing
    description                           : Type faster than ever.
    fontawesome_icon_name                 : play-circle

  - title                                 : Emoji
    description                           : Lots of fun.
    fontawesome_icon_name                 : sync

  - title                                 : Customizable
    description                           : Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : adjust

  - title                                 : Social Links
    description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : link

  - title                                 : FontAwesome Support
    description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : info-circle


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.5
topbar_title_color                        : "rgba(0, 0, 0, 0.6)"

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#000000"
app_price_color                           : "#000000"
app_description_color                     : "#000000"

feature_title_color                       : "#000000"
feature_text_color                        : "#444444"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "rgba(10, 207, 27, 1)"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#000000"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
